[package]
name = "velox"
version = "0.1.5"
edition = "2024"

[dependencies]
winit = "0.30"
glow = "0.16"
nix = { version = "0.30", features = ["fs", "process", "term"] }
bytemuck = "1"
unicode-width = "0.2"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
smallvec = "1"
bitflags = { version = "2", features = ["serde"] }
glutin = "0.32"
glutin-winit = "0.5"
ab_glyph = "0.2"
libc = "0.2"
fontdb = "0.23"
png = "0.17"
owned_ttf_parser = "0.25"

