single_instance = true

[font]
font_family = "monospace"
font_size = 12.0
font_scale_multiplier = 1.5
bold_is_bright = true

[window]
scrollback_limit = 2000
infinite_scrollback = true
gpu_acceleration = true
scroll_multiplier = 5.0
fps_limit = 120
padding_x = 8.0
padding_y = 4.0
cursor_shape = "beam"
cursor_blink = true
scroll_on_output = true
scroll_on_keystroke = true

[colors]
default_fg = "#c6d0f5"
default_bg = "#303446"
black = "#51576d"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#b5bfe2"
bright_black = "#626880"
bright_red = "#e78284"
bright_green = "#a6d189"
bright_yellow = "#e5c890"
bright_blue = "#8caaee"
bright_magenta = "#f4b8e4"
bright_cyan = "#81c8be"
bright_white = "#c6d0f5"
