single_instance = true

[font]
font_family = "monospace"
font_size = 12.0
font_scale_multiplier = 1.5
bold_is_bright = true

[window]
scrollback_limit = 2000
infinite_scrollback = true
gpu_acceleration = true
scroll_multiplier = 5.0
fps_limit = 120
padding_x = 8.0
padding_y = 4.0
cursor_shape = "beam"
cursor_blink = true
scroll_on_output = true
scroll_on_keystroke = true

[colors]
default_fg = "#e0def4"
default_bg = "#191724"
black = "#26233a"
red = "#eb6f92"
green = "#9ccfd8"
yellow = "#f6c177"
blue = "#31748f"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"
bright_black = "#6e6a86"
bright_red = "#eb6f92"
bright_green = "#9ccfd8"
bright_yellow = "#f6c177"
bright_blue = "#31748f"
bright_magenta = "#c4a7e7"
bright_cyan = "#ebbcba"
bright_white = "#e0def4"
