single_instance = true

[font]
font_family = "monospace"
font_size = 12.0
font_scale_multiplier = 1.5
bold_is_bright = true

[window]
scrollback_limit = 2000
infinite_scrollback = true
gpu_acceleration = true
scroll_multiplier = 5.0
fps_limit = 120
padding_x = 8.0
padding_y = 4.0
cursor_shape = "beam"
cursor_blink = true
scroll_on_output = true
scroll_on_keystroke = true

[colors]
default_fg = "#575279"
default_bg = "#faf4ed"
black = "#f2e9de"
red = "#b4637a"
green = "#286983"
yellow = "#ea9d34"
blue = "#56949f"
magenta = "#907aa9"
cyan = "#d7827e"
white = "#575279"
bright_black = "#9893a5"
bright_red = "#b4637a"
bright_green = "#286983"
bright_yellow = "#ea9d34"
bright_blue = "#56949f"
bright_magenta = "#907aa9"
bright_cyan = "#d7827e"
bright_white = "#575279"
