use crate::config::config::{Config, ConfigColors};

pub fn default_config() -> Config {
    Config {
        font_family: "monospace".to_string(),
        font_size: 14.0,
        shell: None,
        default_fg: Some("#F8F8F2".to_string()),
        default_bg: Some("#272822".to_string()),
        colors: Some(ConfigColors {
            black: Some("#272822".to_string()),
            red: Some("#F92672".to_string()),
            green: Some("#A6E22E".to_string()),
            yellow: Some("#F4B575".to_string()),
            blue: Some("#66D9EF".to_string()),
            magenta: Some("#AE81FF".to_string()),
            cyan: Some("#A1EFE4".to_string()),
            white: Some("#F8F8F2".to_string()),
            bright_black: Some("#75715E".to_string()),
            bright_red: Some("#F92672".to_string()),
            bright_green: Some("#A6E22E".to_string()),
            bright_yellow: Some("#F4B575".to_string()),
            bright_blue: Some("#66D9EF".to_string()),
            bright_magenta: Some("#AE81FF".to_string()),
            bright_cyan: Some("#A1EFE4".to_string()),
            bright_white: Some("#F8F8F0".to_string()),
        }),
        scrollback_limit: Some(1000),
        infinite_scrollback: Some(false),
        gpu_acceleration: Some(true),
        scroll_multiplier: Some(1.0),
        fps_limit: Some(120),
        bold_is_bright: Some(true),
        app_title: None,
        padding_x: Some(8.0),
        padding_y: Some(4.0),
        font_scale_multiplier: Some(1.5),
        cursor_shape: Some("block".to_string()),
        cursor_blink: Some(true),
        single_instance: Some(true),
    }
}
